- name: install tmux
  include_role:
    name: yum_apt_retry
  vars:
    package:
      - tmux
    creates:
      - /usr/bin/tmux
- name: add sudo permissions
  lineinfile:
    path: /etc/sudoers
    regexp: '^{{site}}.*yum'
    line: "{{site}}  ALL=(ALL) NOPASSWD: /usr/bin/omd, NOPASSWD: /usr/bin/dnf, NOPASSWD:SETENV: /usr/bin/apt-get"

- name: git init
  include_role:
    name: site_git