- name: "yum install local test perl dependencies"
  include_role:
    name: yum_apt_retry
  vars:
    package:
      - diffutils
      - expect  # contains unbuffer
    rpm:
      - perl-Test-Harness
      - perl-ExtUtils-Manifest
      - perl-ExtUtils-Install
    creates:
      - /usr/bin/unbuffer
      - /usr/bin/diff
      - /usr/share/perl5/vendor_perl/Test/Harness.pm
      - "/usr/share/perl5/vendor_perl/ExtUtils/Manifest.pm,/usr/share/perl/*/ExtUtils/Manifest.pm"
      - "/usr/share/perl5/vendor_perl/ExtUtils/Install.pm,/usr/share/perl5/ExtUtils/Install.pm"
- lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=C.utf8'
- name: install local_test.sh
  copy:
    src: "{{ role_path }}/files/local_test.sh"
    dest: "/usr/local/bin/local_test.sh"
    mode: "755"
