- name: "yum install local test perl dependencies"
  include_role:
    name: yum_apt_retry
  vars:
    package:
      - diffutils
      - expect  # contains unbuffer
    rpm:
      - perl-Test-Harness
      - perl-ExtUtils-Manifest
      - perl-ExtUtils-Install
    creates:
      - /usr/bin/unbuffer
      - /usr/bin/diff
      - /usr/share/doc/perl-Test-Harness
      - /usr/share/doc/perl-ExtUtils-Manifest
      - /usr/share/doc/perl-ExtUtils-Install
- lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=C.utf8'
- name: install local_test.sh
  copy:
    src: "{{ role_path }}/files/local_test.sh"
    dest: "/usr/local/bin/local_test.sh"
    mode: "755"
